# Hangman Picture Update Function

def PicUpdate(count):

		if count == 1:
			print("You have 9 mistakes left to guess the word or you die")
			print("_____________")
			print("|           |")
			print("|")
			print("|")
			print("|")
			print("|")
			print("|")
			print("|______________|")
			print("|______________|")
		elif count == 2:
			print("You have 8 mistakes left to guess the word or you die")
			print("_____________")
			print("|           |")
			print("|           |")
			print("|")
			print("|")
			print("|")
			print("|")
			print("|______________|")
			print("|______________|")
		elif count == 3:
			print("You have 7 mistakes left to guess the word or you die")
			print("_____________")
			print("|           |")
			print("|           |")
			print("|           O")
			print("|")
			print("|")
			print("|")
			print("|______________|")
			print("|______________|")
		elif count == 4:
			print("You have 6 mistakes left to guess the word or you die")
			print("_____________")
			print("|           |")
			print("|           |")
			print("|           O")
			print("|           |")
			print("|")
			print("|")
			print("|______________|")
			print("|______________|")
		elif count == 5:
			print("You have 5 mistakes left to guess the word or you die")
			print("_____________")
			print("|           |")
			print("|           |")
			print("|           O")
			print("|          -|")
			print("|")
			print("|")
			print("|______________|")
			print("|______________|")
		elif count == 6:
			print("You have 4 mistakes left to guess the word or you die")
			print("_____________")
			print("|           |")
			print("|           |")
			print("|           O")
			print("|          -|-")
			print("|")
			print("|")
			print("|______________|")
			print("|______________|")
		elif count == 7:
			print("You have 3 mistakes left to guess the word or you die")
			print("_____________")
			print("|           |")
			print("|           |")
			print("|           O")
			print("|          -|-")
			print("|          / ")
			print("|")
			print("|______________|")
			print("|______________|")
		elif count == 8:
			print("You have 2 mistakes left to guess the word or you die")
			print("_____________")
			print("|           |")
			print("|           |")
			print("|           O")
			print("|          -|-")
			print("|          / \\")
			print("|")
			print("|______________|")
			print("|______________|")
		elif count == 9:
			print("You have 1 mistake left to guess the word or you die")
			print("_____________")
			print("|           |")
			print("|           |")
			print("|           O")
			print("|          -|-")
			print("|         _/ \\")
			print("|")
			print("|______________|")
			print("|______________|")
		elif count == 10:
			print("You died!")
			print("_____________")
			print("|           |")
			print("|           |")
			print("|           O")
			print("|          -|-")
			print("|         _/ \\_")
			print("|")
			print("|______________|")
			print("|______________|")